* Pre-Configuration
Always ensure the package is installed.
#+begin_src emacs-lisp
(require 'use-package-ensure)
(setq use-package-always-ensure t)
#+end_src

Always compile packages, and use the newest version available.
#+begin_src emacs-lisp
(use-package auto-compile
  :config (auto-compile-on-load-mode))

(setq load-prefer-newer t)
#+end_src

* Text Editing
# TODO: Highlight FIX/TODO/BUG
# 12. company for elisp, especially for completion emacs functions/variables
# 22. Edit comment or string/docstring or code block inside them in separate buffer with your favorite mode
# 10. json with formatter
** Basic Keybindings
*Keybinding Values*:
| Meaning | Emacs Key Value | MacOS Key           |
|---------+-----------------+---------------------|
| Control | =C=               | =Control(Ctrl)=       |
| Meta    | =M=               | =Option(Alt)=         |
| Super   | =s=               | =Command=             |
| Shift   | =S=               | =Shift=               |
| -       | =s-z=             | =Command + Z=         |
| -       | =s-Z=             | =Command + Shift + Z= |

*Keybinding Functions*: [[https://www.masteringemacs.org/article/mastering-key-bindings-emacs][Reference]]
- =(define-key KEYMAP KEY DEF)=: Defines a key against a keyboard map. Use this if you want to change a keymap that isn’t the current buffer map.
- =(local-set-key KEY COMMAND)=: Binds a key to the local keymap used by the active buffer, unlike define-key which takes an explicit keymap to bind a key against.
- =(local-unset-key KEY)=: Removes KEY from the active, local keymap.
- =(global-set-key KEY COMMAND)=: Binds a key to the global keymap, making it available in all buffers (with a caveat – see below.)
- =(global-unset-key KEY)=: Removes KEY from the global keymap

*Keybinding Value Styles*:
- =(kbd "s-Z")=
- ~"s-Z"~
- ~[s-Z]~

Make =Command + ArrowKey= behaves like MacOS app.
- =Command + ↑=: move to the top of the file.
- =Command + ↓=: move to the bottom of the file.
- =Command + ←=: move to the beginning of the line.
- =Command + →=: move to the end of the line.
#+begin_src emacs-lisp
(global-set-key (kbd "s-<up>") 'beginning-of-buffer)
(global-set-key (kbd "s-<down>") 'end-of-buffer)
(global-set-key (kbd "s-<right>") 'move-end-of-line)
(global-set-key (kbd "s-<left>") 'move-beginning-of-line)
#+end_src

=Command + Backspace=: Delete current line from cursor to the beginning
#+begin_src emacs-lisp
(global-set-key (kbd "s-<backspace>") 'backward-kill-line)

(defun backward-kill-line (arg)
  "Kill ARG lines backward."
  (interactive "p")
 (kill-line (- 1 arg)))
#+end_src

=Command + Shift + Backspace=: Delete whole line entirely.\\
/This is not the default behavior of MacOS, but I found it's useful./
#+begin_src emacs-lisp
(global-set-key (kbd "s-S-<backspace>") 'kill-whole-line)
#+end_src


# TODO:
# 1. Comment on empty line, it adds (e.g.) and put the cursor behind
# 2. Comment one line, it adds before and forward one line
# 3. Comment on region, it add and move to the next line of the region
# 4. Cannot uncomment inside org mode code block
=Command + /=: Comment/Uncomment line(s).
#+begin_src emacs-lisp
(global-set-key (kbd "s-/") 'comment-or-uncomment-region-or-line)

(defun comment-or-uncomment-region-or-line ()
  "Comments or uncomments the region or the current line if
there's no active region."
  (interactive)
  (let (beg end)
    (if (region-active-p)
        (setq beg (region-beginning) end (region-end))
      (setq beg (line-beginning-position) end (line-end-position)))
    (comment-or-uncomment-region beg end)))
#+end_src
** Evil Mode
[[https://github.com/emacs-evil/evil][Evil]] is an extensible vi layer for Emacs. It emulates the main features of Vim, and provides facilities for writing custom extensions.
#+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))
#+end_src

Relative line number for normal mode, absolute line number for insert mode.
#+begin_src emacs-lisp
(defun my/display-set-relative ()
  (setq display-line-numbers 'relative))

(defun my/display-set-absolute ()
  (setq display-line-numbers t))

(add-hook 'evil-insert-state-entry-hook #'my/display-set-absolute)
(add-hook 'evil-insert-state-exit-hook #'my/display-set-relative)
#+end_src

# FIX: Not working
Unbind =return= key in for using it to open link in org mode.
#+begin_src emacs-lisp
(with-eval-after-load 'evil-maps
    (define-key evil-motion-state-map (kbd "RET") nil))
#+end_src

Set Evil cursor color and styles in different situations.
You can try these commands independently to test the effects: =Esc, i, v, d, r=
#+begin_src emacs-lisp
(setq evil-normal-state-cursor '(box "#e2416c")
      evil-insert-state-cursor '(bar "#e2416c")
      evil-visual-state-cursor '(hollow "#e2416c")
      evil-operator-state-cursor '(evil-half-cursor "#e2416c")
      evil-replace-state-cursor '(hbar "#e2416c"))
#+end_src
*** Evil Collection
[[https://github.com/emacs-evil/evil-collection][evil-collection]], which provides evil-friendly bindings for many modes.
#+begin_src emacs-lisp
(use-package evil-collection
  :after evil
  :config
  (setq evil-collection-mode-list
        '(dired magit))
  (evil-collection-init))
#+end_src

*** Evil Surround
[[https://github.com/emacs-evil/evil-surround][evil-surround]] makes surround text with paired symbols easily.
#+begin_src emacs-lisp
(use-package evil-surround
  :after evil
  :config
  (global-evil-surround-mode 1))
#+end_src

*** Undo Fu
[[https://gitlab.com/ideasman42/emacs-undo-fu][Undo Fu]] is a simple, stable linear undo with redo.
#+begin_src emacs-lisp
(use-package undo-fu
  :config
  (define-key evil-normal-state-map "u" 'undo-fu-only-undo)
  (define-key evil-normal-state-map "\C-r" 'undo-fu-only-redo))

(global-unset-key (kbd "s-z"))
(global-set-key (kbd "s-z")   'undo-fu-only-undo)
(global-set-key (kbd "s-Z") 'undo-fu-only-redo)
#+end_src

[[https://gitlab.com/ideasman42/emacs-undo-fu-session][Undo fu session]] writes undo/redo information upon file save which is restored where possible when the file is loaded again.
#+begin_src emacs-lisp
(use-package undo-fu-session
  :config
  (setq undo-fu-session-incompatible-files '("/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'")))

(global-undo-fu-session-mode)
#+end_src

** Multiple Cursor
** Behavior
Auto pair brackets, quotes etc.
#+begin_src emacs-lisp
(electric-pair-mode 1)
#+end_src

Overwrite selection on pasting.
#+begin_src emacs-lisp
(delete-selection-mode 1)
#+end_src

Delete trailing whitespace on saving a buffer.
#+begin_src emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

Treat CamelCaseSubWords as separate words in programming mode.
#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'subword-mode)
#+end_src

Indent with 2 space.
#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq indent-line-function 'insert-tab)
#+end_src
* Markup Language
** Org Mode
[[https://orgmode.org/][Org]] is a highly flexible structured plain text file format.
# 6. default with org mode
# 15. org render code block with hiding begin & end
# 16. org valign
# 17. org latex
# 18. Enable partial horizontal scroll in Emacs: https://github.com/misohena/phscroll
# 19. Smooth scrolling over images in Emacs
# 20. Preview equations live in org-mode
# 23. org roam
# Make not*Bold*AtAll work!
Enable headline and subcontent in the indented view.
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
#+end_src

Hide emphasis makers.
#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src

Enable shift selection.
#+begin_src emacs-lisp
(setq org-support-shift-select t)
  ;; (font-lock-add-keywords nil '(("\\b\\(FIXME\\|TODO\\|BUG\\)\\b" 1 font-lock-warning-face t)))
#+end_src
*** Org Superstar
[[https://github.com/integral-dw/org-superstar-mode][Org Superstar]] prettifies headings and plain lists in Org mode.
#+begin_src emacs-lisp
(use-package org-superstar
  :config
  (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
  (setq org-hide-leading-stars t))
#+end_src

Change org headline styles.
#+begin_src emacs-lisp
(setq org-superstar-headline-bullets-list '("◉" "○" "◈" "◇" "▣" "□"))
#+end_src

Change org unordered list styles.
#+begin_src emacs-lisp
(setq org-superstar-prettify-item-bullets t)
(setq org-superstar-item-bullet-alist '((?* . ?•)
                                        (?+ . ?•)
                                        (?- . ?•)))
#+end_src
** Markdown Mode
[[https://github.com/jrblevin/markdown-mode][Markdown]] allows you to write using an easy-to-read, easy-to-write plain text format.
#+begin_src emacs-lisp
(use-package markdown-mode
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init (setq markdown-command "multimarkdown"))
#+end_src
* UI
# 4. Better modeline
- Tab bar and Side bar are not needed.
- Mode line means Status bar.

Disable tool bar.
#+begin_src emacs-lisp
(tool-bar-mode 0)
#+end_src

Disable scroll bar.
#+begin_src emacs-lisp
(scroll-bar-mode 0)
#+end_src

** Title Bar
Show icon and full path in title bar.
#+begin_src emacs-lisp
(setq frame-title-format
    '(:eval
       (if buffer-file-name
           (abbreviate-file-name buffer-file-name)
           "%b")))
#+end_src

** Line Number
Default line number width with 3 characters.
#+begin_src emacs-lisp
(setq-default display-line-numbers-width 3)
#+end_src

** Mode Line
#+begin_src emacs-lisp
(use-package doom-modeline
  :init (doom-modeline-mode 1))
(setq doom-modeline-buffer-encoding nil)
(setq doom-modeline-indent-info t)
(setq column-number-mode t)
(dolist (modeline-face '(
      doom-modeline-buffer-path
      doom-modeline-buffer-file
      doom-modeline-project-dir
      doom-modeline-buffer-modified
      doom-modeline-buffer-major-mode
      doom-modeline-info))
  (set-face-attribute modeline-face nil :weight 'normal))
#+end_src

Hide file icon and file name in mode line.
#+begin_src emacs-lisp
(doom-modeline-def-segment buffer-info
  "buffer info segment."
  "")
(doom-modeline-def-segment buffer-info-simple
  "simple buffer info segment."
  "")
#+end_src

Count column number from 1 instead of 0.
#+begin_src emacs-lisp
(setq column-number-indicator-zero-based nil)
#+end_src
** Font
#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :font "SF Mono-18")
#+end_src

#+begin_src emacs-lisp
(global-set-key (kbd "s-0") 'reset-font-size)
(global-set-key (kbd "s-=") 'text-scale-increase)
(global-set-key (kbd "s--") 'text-scale-decrease)
(defun reset-font-size ()
  (interactive)
  (text-scale-set 0))
#+end_src

Use macOS's default font for Chinese characters.
# Cannot soft wrap line for Chinese characters.
#+begin_src emacs-lisp
(set-fontset-font "fontset-default" 'han '("STHeiti"))
#+end_src
** Behavior
Highlight urls and make them clickable.
#+begin_src emacs-lisp
(goto-address-mode 1)
#+end_src

Highlight paired brackets, includes (), [], {} and so on...
#+begin_src emacs-lisp
(show-paren-mode 1)
(require 'paren)
(set-face-background 'show-paren-match (face-background 'default))
(set-face-foreground 'show-paren-match "#f7d451")
(set-face-attribute 'show-paren-match nil :weight 'extra-bold)
#+end_src

Enable word wrap globally.
#+begin_src emacs-lisp
(global-visual-line-mode 1)
#+end_src

* UX
# 2. Absolute line number in Insert mode
# 5. y or n for yes or no, not work for now
# 11. snails? ivy?
# 21. System-wide popup Emacs windows for quick edits
Disable startup screen.
#+begin_src emacs-lisp
(setq inhibit-startup-screen t)
#+end_src

Empty scratch file on init.
#+begin_src emacs-lisp
(setq initial-scratch-message nil)
#+end_src

Save cursor position for each file.
#+begin_src emacs-lisp
(save-place-mode t)
#+end_src

Save/Restore opened files and windows configuration.
#+begin_src emacs-lisp
(desktop-save-mode 1)
#+end_src

Save files automatically.
#+begin_src emacs-lisp
(auto-save-visited-mode 1)
#+end_src

Ensure files end with newline.
#+begin_src emacs-lisp
(setq require-final-newline t)
#+end_src

Revert (update) buffers automatically when underlying files are changed externally.
#+begin_src emacs-lisp
(global-auto-revert-mode t)
#+end_src

Display relative line numbers on text mode and code mode.
#+begin_src emacs-lisp
(setq-default display-line-numbers-type 'visual
              display-line-numbers-current-absolute t)
(add-hook 'text-mode-hook #'display-line-numbers-mode)
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
#+end_src

Cancel partially typed or accidental command.
#+begin_src emacs-lisp
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))
#+end_src

Ask =y= or =n= instead of =yes= or =no=.
#+begin_src sh
(fset 'yes-or-no-p 'y-or-n-p)
#+end_src

Disable the ring bell when scroll beyond the document.
#+begin_src emacs-lisp
(setq ring-bell-function 'ignore)
#+end_src

When you double-click on a file in the Mac Finder open it as a buffer in the existing Emacs frame, rather than creating a new frame just for that file.
#+begin_src emacs-lisp
(setq ns-pop-up-frames nil)
#+end_src

* Frame
=Ctrl + Command + F=: Set window full screen.
#+begin_src emacs-lisp
(global-set-key (kbd "C-s-f") 'toggle-frame-fullscreen)
#+end_src

=Command + N=: Create new window, default with org-mode and evil-mode
#+begin_src emacs-lisp
(global-set-key (kbd "s-n") 'new-empty-frame)
#+end_src

=Shift + Command + W=: Close current window.
#+begin_src emacs-lisp
(global-set-key (kbd "s-W") 'delete-frame)
#+end_src

TODO: Make the buffers independent in each frame.
#+begin_src emacs-lisp
(defun new-empty-frame ()
  "Create a new frame with a new empty buffer. With org-mode and evil-mode enabled."
  (interactive)
  (let ((buffer (generate-new-buffer "untitled")))
    (set-buffer buffer)
    (org-mode)
    (evil-mode 1)
    (display-buffer buffer '(display-buffer-pop-up-frame . nil))))
#+end_src

* Buffer
Unset =Command + K== for kill buffer.
#+begin_src emacs-lisp
(global-unset-key (kbd "s-k"))
#+end_src

=Command + W=: Close current buffer.
#+begin_src emacs-lisp
(global-set-key (kbd "s-w") 'kill-this-buffer)
#+end_src

# TODO: Command + T for a new buffer.
* Git
** Magit
[[https://github.com/magit/magit][Magit]] is an interface for [[https://git-scm.com/][Git]] inside Emacs.
#+begin_src emacs-lisp
(use-package magit
  :config
(setq magit-diff-refine-hunk t))
#+end_src

** Git Gutter
[[https://github.com/emacsorphanage/git-gutter][Git Gutter]] shows file changes in the left margin.
#+begin_src emacs-lisp
(use-package git-gutter
  :config
  (global-git-gutter-mode 't))
#+end_src

# FIX: Update provide more intelligent solution
Update all window when Emacs focus in.
/This fixes git gutter cannot update the file status after committing outside of Emacs./
#+begin_src emacs-lisp
(add-hook 'focus-in-hook 'git-gutter:update-all-windows)
#+end_src

* Terminal
** Exec Path From Shell
[[https://github.com/purcell/exec-path-from-shell][exec-path-from-shell]] ensures environment variables inside Emacs look the same as in the user's shell.
#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :config
  (exec-path-from-shell-initialize))
#+end_src

** Vterm
# Open as a mini buffer
# Disable evil in vterm
[[https://github.com/akermu/emacs-libvterm][Vterm]] is fully capable, fast, and it can seamlessly handle large outputs.
#+begin_src emacs-lisp
(use-package vterm)
#+end_src

* Chinese
This requires [[https://github.com/daipeihust/im-select][im-select]] to be installed.

Auto switch to English input method and save the previous input
method when entering Evil normal mode, restore the saved input method
when switching back to Evil insert mode.
#+begin_src emacs-lisp
(use-package evil-switch-input-method
  :load-path "~/.config/emacs/elisp/")
#+end_src

Break lines normally for Chinese characters in visual line mode.
#+begin_src emacs-lisp
(setq word-wrap-by-category t)
#+end_src

# FIX: Line Spacing default with Chinese Characters like 。
